command spell
Fate-Grand-Automata/FGA pull request #1880
Opened 2024-08-15 07:15 UTC by ArthurKun21

# command spell

## Pull Request Type

- [ ] Bugfix
- [X] Feature Implementation
- [ ] Documentation
- [ ] Other

## Related issue

- fixes  #1869

## Description

Allows the usage of command spell. Features tracking of command spell and shows warning when used up to 3 times inside the script.

## Screenshots 

Main Screen

![image](https://github.com/user-attachments/assets/fa44a1e4-a1f4-4c25-890b-2ff346fd4ba9)

Command Spell Screen

![image](https://github.com/user-attachments/assets/d6d44e41-2e1e-43f4-8cd8-21b691918109)

---

Ran out of Command Spell

Main Screen

![image](https://github.com/user-attachments/assets/ef6619df-2444-4bcd-87ed-7cb76c867a6d)

Command Spell Screen

![image](https://github.com/user-attachments/assets/2698908f-0376-49df-a9b9-0bd79b0a7046)

---

In use

![HD-Player_FF6MtfLnSn](https://github.com/user-attachments/assets/12b74145-2f44-4580-a210-4821aad406c2)

when ran out

![firefox_0YHl9Wjg6m](https://github.com/user-attachments/assets/b519c6b6-2cf1-4f2b-a06f-87532793dcec)

when deleting the cs usage

![HD-Player_iLJkt043i0](https://github.com/user-attachments/assets/e32b751a-d41d-41ea-90df-706a8ccc54fa)

## Testing 

## Additional context

2025-05-13 04:13 UTC, ArthurKun21 commented
Last time there was a problem with ultrawide screen so I implemented the possible fix bb3f48e59e1730606c38e6417afbab8b307f515e, but I received no further replies when I presented the fix. It should technically work

2025-08-06 01:20 UTC, cy1366371760 commented
Hello, when will this be merged to main branch?

2025-08-06 01:22 UTC, ArthurKun21 commented
I don't know

2025-08-06 22:21 UTC, cy1366371760 commented
> I don't know

Hi, I cloned this branch. It seemed that there are only JP and EN's command spell image. So I added a CN image and it worked smoothly. Thank you for the implementation! Here is the CN image, perhaps you can add it: 
<img width="35" height="12" alt="command_spell" src="https://github.com/user-attachments/assets/03ba9ae9-4203-4b30-821c-b6d89b7b243e" />

2025-08-06 22:27 UTC, ArthurKun21 commented
> Hi, I cloned this branch. It seemed that there are only JP and EN's command spell image. So I added a CN image and it worked smoothly. Thank you for the implementation! Here is the CN image, perhaps you can add it:

can you also tell us your phone specs?

just wanna know if you are on wide/ultrawide screen and if it ever worked out for you. thanks!

2025-08-06 22:41 UTC, cy1366371760 commented
> can you also tell us your phone specs?
> 
> just wanna know if you are on wide/ultrawide screen and if it ever worked out for you. thanks!

My phone screen is 2340 * 1080. I reshape the screenshot into 1560 * 720 and then crop.

2025-08-06 22:49 UTC, ArthurKun21 commented
https://github.com/Fate-Grand-Automata/FGA/blob/e8fc0fd53f3529825fc0887a3122c788c539de6c/scripts/src/main/java/io/github/fate_grand_automata/scripts/FgoGameAreaManager.kt#L65

oh we run things with 1280x720 size

2025-08-08 01:26 UTC, ArthurKun21 commented
I'm going to YOLO this one for you @cy1366371760

2025-08-08 01:47 UTC, cy1366371760 commented
> I'm going to YOLO this one for you @cy1366371760

Thank you!

2025-08-08 01:49 UTC, ArthurKun21 commented
You access the alpha from here https://github.com/Fate-Grand-Automata/FGA/pull/1880#issuecomment-2574161541 it always get autoupdated with each new build from this PR

2025-08-08 23:50 UTC, cy1366371760 commented
> You access the alpha from here [#1880 (comment)](https://github.com/Fate-Grand-Automata/FGA/pull/1880#issuecomment-2574161541) it always get autoupdated with each new build from this PR

Hi, today I use adb command to adjust my phone's resolution to 1280 * 720 size, and remake the screenshot. It is still runnable in my phone, and I guess it will be more robust on other devices: 
<img width="14" height="11" alt="command_spell" src="https://github.com/user-attachments/assets/905c4ad9-6603-46dc-8054-29642ef7cc2d" />

2025-08-08 23:55 UTC, ArthurKun21 commented
> It is still runnable in my phone, and I guess it will be more robust on other devices:

I'm going to take your word for this and update the build with your latest template image.

2025-08-17 20:10 UTC, reconman requested changes
Can you please remove the HP refill option and make it so the "CS (3)" button triggers the NP charge?

I don't think anyone needs to use the HP refill option when enemy attacks area heavily randomized and most people are only interested in NP refills for Bleached Earth quests.

2025-08-18 00:01 UTC, ArthurKun21 commented
I still think it is better to show the two options even if most people would only use the NP for command spell

2026-06-15 13:15 UTC, ArthurKun21 commented
it has been almost 2 years, I don't think this is going to be possibly be added.

2026-07-16 22:41 UTC, reconman commented
> it has been almost 2 years, I don't think this is going to be possibly be added.

Not with the HP refill option. I would merge it if it was only a refill NP button instead of a separate screen.

2026-08-30 15:46 UTC, merged