Updated Korean translations
Fate-Grand-Automata/FGA pull request #790
Opened 2021-07-28 06:46 UTC by ScathachSkadi

Added new items translations and some UI related translations.

2021-07-28 06:48 UTC, reconman commented on app/src/main/res/values-ko/localized.xml
> -    <string name="support_imgs_extract_failed">서포트 이미지 추출을 실패했습니다</string>
Missing a >

2021-07-28 06:53 UTC, ScathachSkadi commented on app/src/main/res/values-ko/localized.xml
> -    <string name="support_imgs_extract_failed">서포트 이미지 추출을 실패했습니다</string>
Thanks

2021-07-28 06:57 UTC, ScathachSkadi reviewed
> added

2021-07-28 13:34 UTC, item4 commented
there are some useless trailing spaces. can you strip these?

2021-07-30 07:36 UTC, ScathachSkadi commented
@item4 I actually don't have a lot of coding knowledge to figure out what is wrong exactly... Usually MatthewSachin(Not tagging him just in case he is busy) cleans up the messy bits I made. But I do know what is wrong in general. Is there something that teaches me what parts are wrong so that I can do everything by myself next time?

2021-07-30 07:38 UTC, reconman commented
> @item4 I actually don't have a lot of coding knowledge to figure out what is wrong exactly... Usually MatthewSachin(Not tagging him just in case he is busy) cleans up the messy bits I made. But I do know what is wrong in general. Is there something that can teach me what parts are wrong so that I can do everything by myself next time?

He probably means all your added empty lines.

2021-07-30 07:41 UTC, ScathachSkadi commented
@reconman Oh. I did that so I can see what I needed to add side by side with Notepad++. If I delete the empty lines will it be still functional?

2021-07-30 07:42 UTC, reconman commented
Yes, of course.

2021-07-30 07:42 UTC, ScathachSkadi commented
Wow. That is news to me. I'll go do that right now.

2021-07-30 07:49 UTC, ScathachSkadi commented
I hope I did it right.

2021-07-30 20:20 UTC, reconman requested changes

2021-07-30 20:20 UTC, reconman commented on app/src/main/res/values-ko/localized.xml
> +        This accessibility service is used to perform clicks and swipes without root.
This also should be translated.

2021-07-30 22:47 UTC, ScathachSkadi commented on app/src/main/res/values-ko/localized.xml
> +        This accessibility service is used to perform clicks and swipes without root.
Alright.

2021-07-30 22:56 UTC, ScathachSkadi commented on app/src/main/res/values-ko/localized.xml
> +        This accessibility service is used to perform clicks and swipes without root.
I did it. Thanks for letting me know.

2021-07-31 03:11 UTC, item4 commented on app/src/main/res/values-ko/localized.xml
> +    <string name="times_rolled">Rolled %d time(s)</string>
이거 번역이 가능하지 않을까요?
(I think it is translatable.)

2021-07-31 03:21 UTC, ScathachSkadi commented on app/src/main/res/values-ko/localized.xml
> +    <string name="times_rolled">Rolled %d time(s)</string>
Thank you. It has been fixed now.

2021-07-31 08:51 UTC, reconman approved these changes

2021-07-31 08:52 UTC, merged